version: "3.7"
services:
  swing:
    restart: always
    image: piensa/minor:9zs7l9by04s378q6lzxppf15743jk6qw
    volumes:
      - ./swing.py:/lib/python3.7/site-packages/swing.py
      - ./Caddyfile:/Caddyfile
      - ./static:/static
    networks:
      - web
    command: caddy -conf /Caddyfile
    ports:
      - "2015:2015"
    environment:
      - DJANGO_SETTINGS_MODULE=swing.settings
networks:           
 web:  
    external:
      name: swing
